import Mathlib

namespace LeanMathlib

namespace DeFi

/--
An abstract DeFi market system as a state-transition relation.

This deliberately avoids committing to reserves, wallets, fees, or oracle data:
all of those are components of the state type in concrete instantiations.
-/
structure MarketSystem (σ : Type*) where
  Step : σ → σ → Prop

namespace MarketSystem

variable {σ α : Type*}

/-- Finite reachability generated by market transitions. -/
inductive Reachable (M : MarketSystem σ) : σ → σ → Prop
  | refl (s : σ) : Reachable M s s
  | tail {s t u : σ} : Reachable M s t → M.Step t u → Reachable M s u

/-- A scalar market invariant is preserved by every one-step transition. -/
def PreservesInvariant (M : MarketSystem σ) (I : σ → α) : Prop :=
  ∀ {s t : σ}, M.Step s t → I t = I s

/--
`I` strictly increases along a chosen dominance relation.

The dominance relation is intentionally external: different protocols may rank
states by wallet balances, reserves, utility, collateral safety, or bundles of
these quantities.
-/
def StrictlyIncreasesOn [LT α] (dominates : σ → σ → Prop) (I : σ → α) : Prop :=
  ∀ {better worse : σ}, dominates better worse → I worse < I better

/--
An arbitrage witness is a reachable transition from a state to a strictly
dominating state.
-/
def HasArbitrage (M : MarketSystem σ) (dominates : σ → σ → Prop) : Prop :=
  ∃ s t : σ, Reachable M s t ∧ dominates t s

theorem invariant_eq_of_reachable
    (M : MarketSystem σ) (I : σ → α)
    (hPres : M.PreservesInvariant I) {s t : σ}
    (hReach : Reachable M s t) :
    I t = I s := by
  induction hReach with
  | refl => rfl
  | tail hReach hStep ih =>
      calc
        I _ = I _ := hPres hStep
        _ = I _ := ih

theorem not_dominates_of_reachable_preserved_strictInvariant [Preorder α]
    (M : MarketSystem σ) (I : σ → α) (dominates : σ → σ → Prop)
    (hPres : M.PreservesInvariant I)
    (hStrict : StrictlyIncreasesOn dominates I)
    {s t : σ} (hReach : Reachable M s t) :
    ¬ dominates t s := by
  intro hDom
  have hEq : I t = I s := invariant_eq_of_reachable M I hPres hReach
  have hLt : I s < I t := hStrict hDom
  exact (lt_irrefl (I s)) (hLt.trans_eq hEq)

/--
If a market has a preserved invariant that strictly increases along the chosen
dominance relation, then no finite reachable arbitrage exists.
-/
theorem no_arbitrage_of_preserved_strictInvariant [Preorder α]
    (M : MarketSystem σ) (I : σ → α) (dominates : σ → σ → Prop)
    (hPres : M.PreservesInvariant I)
    (hStrict : StrictlyIncreasesOn dominates I) :
    ¬ M.HasArbitrage dominates := by
  rintro ⟨s, t, hReach, hDom⟩
  exact not_dominates_of_reachable_preserved_strictInvariant
    M I dominates hPres hStrict hReach hDom

/-- A one-step invariant immediately rules out one-step dominance arbitrage. -/
theorem not_dominates_of_step_preserved_strictInvariant [Preorder α]
    (M : MarketSystem σ) (I : σ → α) (dominates : σ → σ → Prop)
    (hPres : M.PreservesInvariant I)
    (hStrict : StrictlyIncreasesOn dominates I)
    {s t : σ} (hStep : M.Step s t) :
    ¬ dominates t s :=
  not_dominates_of_reachable_preserved_strictInvariant
    M I dominates hPres hStrict (Reachable.tail (Reachable.refl s) hStep)

end MarketSystem

end DeFi

end LeanMathlib
